name: Datasets

on:
  push:
    paths:
      - 'use-cases/**'
      - '.github/workflows/datasets.yml'
  pull_request:
    paths:
      - 'use-cases/**'
      - '.github/workflows/datasets.yml'

jobs:
  load:
    name: Load dataset
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dataset:
          - bookstore
          - cyber-threat-intelligence
          - identity-and-access-management
          - social-network

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup TypeDB
      uses: typedb/setup-typedb@1.0.0
      with:
        typedb_version: 3.5.5
        typedb_args: "--development-mode.enabled=true"

    - name: Load dataset
      run: |
        typedb console --address=localhost:1729 --tls-disabled \
          --username=admin --password=password \
          --command="database create-init ${{ matrix.dataset}} \
          use-cases/${{matrix.dataset}}/schema.tql \
          use-cases/${{matrix.dataset}}/data.tql"
